POST http://localhost:3333/tarefas
Content-type:application/json

{
    "title": "Passear com o cachorro",
    "description" : "Essa é a minha tarefa",
    "date": "Amanhã",
    "categoria": "Lazer"
}

###

GET http://localhost:3333/tarefas

###

PUT http://localhost:3333/tarefas/
Content-type:application/json

{
    "title": "Passear com o cao",
    "description" : "Essa é a minha tarefa",
    "date": "Amanhã",
    "categoria": "Lazer"
}

###
DELETE http://localhost:3333/tarefas/